name: Swift Build (macOS-Swift5)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos-legacy:
    name: Swift Build (macOS-Swift5)
    runs-on: macos-14
    env:
      DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
    steps:
    - uses: actions/checkout@v4
    - name: Switch to Swift 5 Manifest
      run: mv "Package@swift-5.swift" Package.swift
    - name: Build
      run: swift build -v
